### ISSUE TITLE
Read configuration from external storage (SD card)

### ISSUE THREAD

**Issue by pacien** [pacien/tincapp#2]
Read configuration from the application directory on external storage (SD card) as a secondary option for users who can't write on the internal storage.

Log, PID and socket files will be stored along on the same storage as the active configuration. The recommended option will remain unchanged, as files on the External Storage are world readable, which is a problem for protecting private keys.

- [x] Handle configurations put on External Storage
- [x] Remove the "Fix permissions" option
- [x] <del>Consider</del> removing additional support for internal storage
- [x] Update documentation

**Comment by buckshee** [comment]
Could this simply be an import? we'd then be able to download files to storage, import them into the app's secure space, then delete them (typically download with something like Termux?) There is an OpenVPN client that seems to work like this, the blinkt.de one.

Also there is the Storage Access Framework, exposing files here would allow direct creation and editing with something like Turbo Editor

**Comment by pacien** [comment]
An option to move config files from external to internal storage can indeed be implemented. However this raises questions about how they can be overwritten or exported (basically cancelling all security benefits of the internal storage). I would be in favor of an import-only option.

As for the storage access framework, I would like to avoid as much as possible re-creating a file manager inside the app. Importing hosts files with their public keys would be painful in an Android text editor, especially when ADB or Termux with SSH can do the same more conveniently.

**Comment by buckshee** [comment]
I don't think anything would need exporting except the public key, and that could be shared as text for a send to self via email, or anything else.

What I have been doing with my host files is `scp`ing them from a server,  don't know if this is ideal, but it works for how I'm using it so far, it should actually be `rsync` with --delete eventually.

Since key management is totally user driven for Tinc 1, depending on something like Termux is appropriate. Using `scp` or `rsync` to download the 'hosts' directory and use the directory selection picker in Android. All current hosts should be deleted, there does not need to be any particular sanity checking IMO.

Another way would be a single file to be served from and ad-hoc HTTP server:

`for host in $(ls) ; do echo \#\#$host >> all_hosts ; cat $host >> all_hosts ; done`

Then parse the file based on the double comment, but needs the host name to make the file name.

**Comment by pacien** [comment]
The app can now (as of commit d221543) handle configuration directories on the external storage.
This is temporarily done by adding the `external/` prefix to the network name, until the app gets a real GUI.

Some other thoughts:
- importing the configuration file requires the user to keep another copy of the configuration files on another device, which is not convenient when generating the private key on the device itself
- the configuration could instead be stored encrypted with a passphrase, just like SSH or PGP private keys stored by other apps

I might implement one of those solutions later.
