### ISSUE TITLE
A few questions which might be useful to the FAQ

### ISSUE THREAD

**Issue by doronbehar** [pacien/tincapp#60]
1. Why exactly is switch mode not available? I've got these messages in my `tinc.<network>.log`:
```
2018-08-07 11:57:40 tinc[19236]: Switch mode not supported (requires unsupported TAP device)!
```
2. Why is there `network.conf` **and** `tinc.conf` while `network.conf` is used only when using the app?
3. If I'm running the the app while I'm not connected to a WiFi network, should I be able to ping to the other hosts via their VPN ip address? Allow me to explain my setup:
My Linux laptop is connected to a WiFi hotspot coming from my phone. They both run tinc and my laptop succeeds when trying to ping to my VPS but I get no response when trying to do so with [Termux](https://termux.com/). Since my phone is connected to the internet via GSM I have no option of setting port forwarding or something alike but from some reason, whether I'm pinging to my VPS while the phone it self is running tinc or not, I get good response.
Anyway I wonder if the environment should be taken into consideration at all.

Thanks.

**Comment by pacien** [comment]
Answers to those questions are already present in the [faq](https://tincapp.pacien.org/faq.html), even though they could be phrased and categorized better. I'll update the website with the answers below.

> 1. Why exactly is switch mode not available?

The Android VPN API only exposes a `tun` device to the application, which operates on layer 3 (IP).
It doesn't offer the possibility to use a `tap` device which is required for the layer 2 switch mode.

> 2. Why is there `network.conf` and `tinc.conf` while `network.conf` is used only when using the app?

`network.conf` is used by the Android app to configure the network interface the way it would have been with hook scripts (`tinc-up.sh` and others) on other platforms. This is done using a special configuration file because the Android API requires the interface to be configured _before_ being used and due to the unavailability of a shell interpreter within the application. It also has the purpose of containing additional platform-specific settings to allow only some applications to use the VPN for example.

> 3. [situation where two clients share a common isolated network]

The phone and laptop most likely attempt to establish a connection to the VPS node which acts both as a relay and a helper used to establish a direct connection between the phone and the laptop. Enabling tinc's `LocalDiscovery` feature removes the necessity of a common node to establish direct connections between nodes located on the same network (which would be the phone's hotspot in this case).

**Comment by doronbehar** [comment]
Thanks for the answers to questions 1 and 2.
As for the 3rd question, I've tried setting both in my Laptop and on the app's `tinc.conf` `LocalDiscovery = Yes` and I still get `From 192.168.0.3 icmp_seq=1 Destination Net Unknown` when trying to ping my Phone which it's IP is `192.168.0.3` from my Laptop.

Any Idea why this is happening?

**Comment by pacien** [comment]
Please note that support is mainly provided through the IRC channel #tincapp on freenode.

Regarding the problem, you may want to check the reachability of the node by tapping on their name in the Android app, or using the following command on desktop: `tinc -n $netname info $otherNodeName`.

**Comment by pacien** [comment]
Let's continue on IRC. I'm closing this issue.
