### ISSUE TITLE
Support for encrypted private key

### ISSUE THREAD

**Issue by pacien** [pacien/tincapp#9]
Support optionally passphrase-encrypted private keys. Especially useful when storing everything on the world-readable external storage. The app will show a passphrase prompt if those keys are found to be protected.

- [x] privkeys encryption/decryption
- [x] UI dialogs
- [x] supply decrypted keys to the underlying daemon
- [x] doc update

Notes from IRC:
> guus: You can just do -o PrivateKeyFile=/dev/stdin, and pass a key to tincd that way. Then you have full control over it, and you don't have to write it to rsa_key.priv first.

> guus: this works: cat ed25519_key.priv rsa_key.priv | tincd -o PrivateKeyFile=/dev/stdin -o Ed25519PrivateKeyFile=/dev/stdin

> https://i.stack.imgur.com/5afWK.png
> guus: "a RH A" is the privkey; You'll notice that there's 96 bytes worth of data in ed25519_key.priv after decoding the base64 part. So it's a concatenation of what NaCL's privkey and pubkey.

**Comment by pacien** [comment]
Note from IRC:
> guus: You can just do -o PrivateKeyFile=/dev/stdin, and pass a key to tincd that way.
> Then you have full control over it, and you don't have to write it to rsa_key.priv first.

**Comment by seanho00** [comment]
Thanks for your efforts, pacien!  Perhaps a quick solution might be to put the config dir in private storage (MODE_PRIVATE) on the internal eMMC rather than on the external sdcard?  I think it maps to /data/data/org.pacien.tincapp/.  Could make the config dir user-configurable, if it isn't already.

Seems like the main issue is to find secure storage not readable by other apps (or by SD card readers), and that sounds like something that's been solved before by other Android apps.  Perhaps Android's [KeyStore](https://developer.android.com/training/articles/keystore.html)?

Appreciate that you are reviving the effort to have Tinc1.1 on Android!

**Comment by pacien** [comment]
Hello and thank you for your suggestions @seanho00.

The app was previously storing all configuration data and keys on the internal storage, and provided a way to lock/unlock the app-private directory through the GUI. However, this permission-based trick didn't seemed to be working reliably accross newer Android versions, and some Android file managers still required root access to traverse the filesystem to that directory.

The Android KeyStore works by keeping the keys private private to the system, only allowing cryptographic operations  to be performed through a dedicated API, never exposing the keys back to applications. The tinc app being a wrapper for the tinc daemon, it needs to read those keys directly.

---

Progress update: key encryption/decryption and UI modification are done, remaining work being on transferring those keys to the tinc daemon. I am encountering problems with simple unix pipes on some Android devices, which delays the implementation of this feature.

**Comment by pacien** [comment]
Done for release v0.7.
